
fastlane_version "2.24.0"

default_platform :ios

platform :ios do
  before_all do
    register_devices(devices: {
      "Felix Krause's iPhone 7" => "67b49853d5e977446301bfbd2ad2c7dae96dc562"
    })

    match(git_url: "https://github.com/KrauseFx/certs", type: "appstore")
    match(git_url: "https://github.com/KrauseFx/certs", type: "development", force: true)
  end

  lane :release do
    # gym
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
