fastlane_version "2.24.0"

default_platform :ios

if is_ci
  password = SecureRandom.base64
  keychain_name = "fastlane"
  ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
  ENV["MATCH_KEYCHAIN_PASSWORD"] = password

  create_keychain(
    name: keychain_name,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: true,
    password: password
  )
end

platform :ios do
  before_all do
    register_devices(devices: {
      "Felix Krause's iPhone 7" => "67b49853d5e977446301bfbd2ad2c7dae96dc562"
    })

    match(type: "appstore", readonly: is_ci)
    match(type: "development", readonly: is_ci)
  end

  lane :beta do
    gym(scheme: "wwdcfamily")
    testflight
  end
end
